# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Give the palette a name
palette = 'dracula'

# Insert blank line between shell prompts
add_newline = true

# Set timeout for command
command_timeout = 1000

# Set timeout for scan
scan_timeout = 35

# Format right side of the terminal

# Format the prompt
format = """
[](bg:red fg:background)\
$os\
[](fg:red bg:orange)\
$hostname\
[](fg:orange bg:yellow)\
$username\
[](fg:yellow bg:green)\
$directory\
[](fg:green bg:cyan)\
$git_branch\
$git_status\
$git_state\
$git_metrics\
[](fg:cyan bg:purple)\
$python\
$lua\
$nodejs\
$rust\
[](fg:purple bg:pink)\
$package\
[](fg:pink bg:red)\
$docker_context\
[](fg:red)\
$fill\
[](bg:orange fg:background)\
$time\
[](fg:orange bg:yellow)\
$battery\
[](fg:yellow bg:green)\
$cmd_duration\
[](fg:green bg:cyan)\
$status\
[](fg:cyan bg:purple)\
$jobs\
[](fg:purple)\
$line_break\
$character"""

[os]
format = '[$symbol ]($style)'
style = 'bg:red fg:bright_red'
disabled = false

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
Macos = "󰀵"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[hostname]
ssh_only = false
format = '[$hostname ]($style)'
disabled = false
style = 'bg:orange fg:bright_orange'

[username]
style_user = 'bg:yellow fg:bright_yellow'
style_root = 'bg:yellow fg:bright_yellow'
format = '[$user ]($style)'
disabled = false
show_always = true

[directory]
truncation_length = 3
truncation_symbol = '../'
style = 'bg:green fg:bright_green'
format = '[$path ]($style)'
truncate_to_repo = false

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = ""
"Music" = "󰝚"
"Pictures" = ""
"Developer" = "󰲋"
"Code" = "󰲋"

[git_branch]
symbol = ""
format = '[$symbol $branch ]($style)'
style = 'bg:cyan fg:bright_cyan'

[git_status]
style = 'bg:cyan fg:bright_cyan'
format = '([$all_status $ahead_behind ]($style))'
conflicted = '[conflicted=${count} ](bg:cyan fg:bright_red)'
up_to_date = '[up-to-date ](bg:cyan fg:bright_green)'
untracked = '[untracked=${count} ](bg:cyan fg:bright_red)'
ahead = 'ahead=${count}(fg:bright_purple bg:cyan) '
diverged = 'ahead=${ahead_count} behind=${behind_count}(fg:bright_purple bg:cyan) '
behind = 'behind=${count}(fg:bright_red bg:cyan) '
stashed = '[stashed=${count} ](fg:bright_red bg:cyan)'
modified = '[modified=${count} ](fg:bright_yellow bg:cyan)'
staged = '[staged=${count} ](fg:bright_yellow bg:cyan)'
renamed = '[renamed=${count} ](fg:bright_yellow bg:cyan)'
deleted = '[deleted=${count} ](fg:bright_red bg:cyan)'

[git_state]
style = 'bg:cyan fg:bright_cyan'
format = '[$state ($progress_current/$progress_total) ]($style)'

[git_metrics]
added_style = 'bg:cyan fg:bright_green'
deleted_style = 'bg:cyan fg:bright_red'
disabled = false
format = '[+$added ]($added_style)[-$deleted ]($deleted_style)'

[python]
style = 'bg:purple fg:bright_purple'
symbol = ' '
format = '[${symbol} (${version}) ]($style)'

[lua]
format = '[${symbol} (${version}) ]($style)'
symbol = ' '
style = 'bg:purple fg:bright_purple'

[nodejs]
style = 'bg:purple fg:bright_purple'
format = '[${symbol} (${version}) ]($style)'
symbol = ' '

[rust]
style = 'bg:purple fg:bright_purple'
format = '[${symbol} (${version}) ]($style)'
symbol = ' '

[ruby]
style = 'bg:purple fg:bright_purple'
format = '[${symbol} (${version}) ]($style)'
symbol = ' '

[package]
symbol = '󰏗 '
disabled = false
style = 'bg:pink fg:bright_pink'
format = '[${symbol} (${version}) ]($style)'

[docker_context]
symbol = ' '
style = 'bg:red fg:bright_red'
format = '[$symbol ]($style)$path '
detect_files = ['docker-compose.yml', 'docker-compose.yaml', 'Dockerfile']
detect_extensions = ['Dockerfile']

[time]
disabled = false
time_format = "%R"
style = 'bg:orange fg:bright_orange'
format = '[󰥔 $time ]($style)'

[battery]
disabled = false
full_symbol = "󰁹"
charging_symbol = "󰂄"
discharging_symbol = "󰂃"
unknown_symbol = "󰁽"
empty_symbol = "󰂎"
format = "[[$symbol ](fg:bright_yellow bg:yellow)]($style)"

[[battery.display]]
threshold = 100
style = 'bg:yellow fg:bright_yellow'

[cmd_duration]
min_time = 500
style = 'bg:green fg:bright_green'
format = '[$duration ]($style)'

[status]
disabled = false
style = "bg:cyan fg:bright_cyan"
format = '[✖  $status ]($style)'
map_symbol = true
recognize_signal_code = true

[jobs]
symbol = ' '
style = 'bg:purple fg:bright_purple'
number_threshold = 1
format = '[$symbol ]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:green)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:green)'
vimcmd_replace_one_symbol = '[](bold fg:purple)'
vimcmd_replace_symbol = '[](bold fg:purple)'
vimcmd_visual_symbol = '[](bold fg:yellow)'

[palettes.dracula]
red='#FF5555'
orange='#FFB86C'
yellow='#F1FA8C'
green='#50FA7B'
cyan='#8BE9FD'
purple='#BD93F9'
pink='#FF79C6'
bright_red='#CB3A2A'
bright_orange='#A34D14'
bright_yellow='#846E15'
bright_green='#14710A'
bright_cyan='#036A96'
bright_purple='#644AC9'
bright_pink='#A3144D'
background='#282A36'
foreground='#F8F8F2'
current_line='#6272A4'
selection='#44475A'
comment='#6272A4'
bright_background='#FFFBEB'
bright_foreground='#1F1F1F'
bright_current_line='#6C664B'
bright_selection='#CFCFDE'
bright_comment='#6C664B'
